### PR TITLE
Chore

### PR DESCRIPTION
**Pull request by kzlsakal**

### CODE REVIEW

**Review by james-b-olivas — APPROVED** [review]

**Comment by kzlsakal** [comment]
[Move the COPY command prompt from the db setup script to db generate script (XS)](https://trello.com/c/1KPUgqSJ/28-move-the-copy-command-prompt-from-the-db-setup-script-to-db-generate-script-xs)

**Comment by kzlsakal** [comment]
[Update README with new environment variables, scripts, and Grunt workflow (M)](https://trello.com/c/Gbe8Y0LM/24-update-readme-with-new-environment-variables-scripts-and-grunt-workflow-m)

**Comment by kzlsakal** [comment]
[Clean up commented out code in index.html (XS)](https://trello.com/c/J2vPTsp7/23-clean-up-commented-out-code-in-indexhtml-xs)

**Comment by kzlsakal** [comment]
[Implement CircleCI (M)](https://trello.com/c/cZLhrSVZ/31-implement-circleci-m)

**Pull request merged**
