### PR TITLE
Refactor legacy back-end code

### PR DESCRIPTION
**Pull request by kzlsakal**

### CODE REVIEW

**Comment by kzlsakal** [comment]
[Add code coverage reporting for back-end (S)](https://trello.com/c/whHLDLFF/6-add-code-coverage-reporting-for-back-end)

**Comment by kzlsakal** [comment]
[Fix test crashing due to webpack loading png file & move test files to the spec folder (XS)](https://trello.com/c/IfJ18SJM/4-fix-test-crashing-due-to-webpack-loading-png-file)

**Comment by kzlsakal** [comment]
[Switch to Hack Reactor Styling Guide (XS)](https://trello.com/c/Y3NB1161/5-switch-to-hack-reactor-styling-guide)

**Comment by kzlsakal** [comment]
[Refactor previous seeding script to exit node process gracefully (XS)](https://trello.com/c/edilPH46/3-refactor-previous-seeding-script-to-exit-node-process-gracefully)

**Review by james-b-olivas — APPROVED** [review]

**Pull request merged**
